services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: fleetwave
      POSTGRES_USER: fleet
      POSTGRES_PASSWORD: fleet
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fleet -d fleetwave || exit 1"]
      interval: 3s
      timeout: 3s
      retries: 20
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:

