version: '3.8'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: fleetwave
      POSTGRES_USER: fleet
      POSTGRES_PASSWORD: fleet
    ports: ["5432:5432"]
    volumes: ["pgdata:/var/lib/postgresql/data"]
volumes:
  pgdata:
