server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fleetwave?options=-c%20TimeZone=America/New_York
    username: fleet
    password: fleet
    # Don't fail fast if DB isn't ready yet
    hikari:
      initializationFailTimeout: 0
      connectionTimeout: 30000

  jpa:
    # Make dialect explicit so Hibernate doesn't need metadata up-front
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate.jdbc.time_zone: UTC

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true

notif:
  email:
    provider: ses
  sms:
    provider: twilio

management:
  endpoints:
    web:
      exposure:
        include: health,info,mappings,beans

