spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fleetwave
    username: fleetwave
    password: fleetwave
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics


# Notifications (provider defaults and tenant overrides)
notif:
  email:
    provider: ses   # ses|smtp|mailgun
    from: no-reply@fleetwave.org
    tenants:
      ocps:
        provider: smtp
        from: dispatch@ocps.fleetwave.org
  sms:
    provider: twilio
    from: "+15555550123"
